BASE_TASK_CONFIG_PATH: "configs/sound_eventnav/av_nav/sound_eventgoal_binaural_test.yaml"
NUM_PROCESSES: 10
SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR"]
TEST_EPISODE_COUNT: 1000
VIDEO_OPTION: []
VISUALIZATION_OPTION: []

EVAL:
  SPLIT: "test"
  USE_CKPT_CONFIG: True